### ISSUE TITLE
BREAKING CHANGE: termselcrit --> termselection

### ISSUE THREAD

**Issue by RieksJ** [tno-terminology-design/mrgt#1]
See [tev2-specifications#17](https://github.com/tno-terminology-design/tev2-specifications/issues/17)

**Comment by RieksJ** [comment]
@Ca5e I just might have covered it all, pls check

**Comment by Ca5e** [comment]
[Should be covered!](https://github.com/tno-terminology-design/tev2-specifications/issues/17)
