### ISSUE TITLE
Hyperlinks to bodyfiles are not correct

### ISSUE THREAD

**Issue by RieksJ** [tno-terminology-design/mrgt#4]
In the tev2-specifications repo, all tools (e.g., mrgt, trrt, etc.) have a term that is defined, and the header in that file specifies a body file, which is typically something like `<dd>-<term>.md`.  The path, relative to `scopedir`, and including the file name, is specified in the `bodyFile` field of the header of the curated text that defines the term, as specified.

When the static site is generated, you can go to a page that describes a tool, which also contains the term describing the tool. If you hover over it, you get its definition, and in the bottom left corner you can see where it will link to when you click on it. The below figure shows that this link is incorrect. 

![image](https://github.com/tno-terminology-design/trrt/assets/8522589/a270ab25-a042-4614-8670-187298314040)

Apparently, the TRRT assumes that the name of the file is `<term>.md`, where in fact it can be an arbitrary name. The last part of the hyperlink should be replaced by the value of the header-field, whose name is specified in the `bodyFileID` field of the SAF.

**Comment by Ca5e** [comment]
More information in https://github.com/tno-terminology-design/mrgt/issues/5 as well.
