### ISSUE TITLE
Feature Request: enable Dual Use of (markdown) documents

### ISSUE THREAD

**Issue by RieksJ** [tno-terminology-design/mrgt#5]
The context for this FR is one in which a lot of documentation exists, and there are various (markdown) files in that documentation that, while serving their own purposes within the context of that documentation, could also be used as a curated text, i.e. a document that describes characteristics of a term. For example, in an architecture description that has a markdown page for every stakeholder-role, that page has its purpose in the architecture documentation, but it could also serve as the curated text associated with the term that is the name of the stakeholder-role.

We do not want create a copy of that file that would then serve as a curated text, because that would cause synchronization problems when the text is updated. Also, we do not want to move the file into the `curatedir`, because it would disrupt the structure of the existing documentation.

The question thus is how we can facilitate the 'dual use' of such files.

One (of possibly more) solution(s) would be to do the following for every such existing document/file:
- create a terms-file, similar as other existing terms, in the `curatedir`, for the term to be defined - as usual;
- add a field in the frontmatter, whose value allows the TRRT to produce a hyperlink to the existing document;
- make sure there is a TRRT-converter that is aware of such a field, and that produces the correct hyperlink if its value is non-null

Questions:
1. Are there any other solutions that are easier/better/... such that we should consider them (as well)?
2. What would be a good name for such a field?
3. Does it make sense to include the converter (and related documentation for use) as an example of how converters can be used, such that users that want to use it can copy/paste the stuff from the documentation and use it themselves?
4. Can the value for such fields be specified such that it works both in the context of a local development and other development contexts?

**Comment by Ca5e** [comment]
Closed as MRGT v0.1.5 is now released with bodyFile functionality related to the use of bodyFileID.
