### ISSUE TITLE
Unexplainable warning after a 'rename'

### ISSUE THREAD

**Issue by RieksJ** [tno-terminology-design/mrgt#9]
Inspecting the [log of the deploy run](https://github.com/tno-terminology-design/tev2-specifications/actions/runs/6668353715/job/18123747330) on commit 3e9e885, I saw the following:

![image](https://github.com/tno-terminology-design/mrgt/assets/8522589/1638c7c5-c8c2-4f58-8d56-cbc5146ccf3a)

This is the result of the following set of termselection instructions:

~~~
- vsntag: documentation # terms that are needed for this specification
  altvsntags: [ latest ] # alternative verstiontags
  termselection:
  - "term[actor,action,community,control,entity,knowledge]@essif-lab"
  - "rename action [term:act, formPhrases:'act{ss}']"
  - "term[action]@essif-lab"
...
~~~

The idea is that after having selected the 6 essif-lab terms, the then selected term `action` is to be renamed, in that its `term` field becomes `act`, and also the `formPhrases` field is adjusted. 

The subsequent instruction `"term[action]@essif-lab"` should then select (for the second time) the associated mrg-entry from the essif-lab MRG. However, this results in an error: the mrg-entry seems to no longer exist.

This seems to me a bug.

**Comment by Ca5e** [comment]
The entries were being added to the Terminology under Construction as a reference to the interpreted MRG, this caused both the MRG entry and TuC entry to be modified on a rename action. 
This will be changed in MRGT v0.1.6 by the [use shallow copy to add entries to TuC](https://github.com/tno-terminology-design/mrgt/commit/4b089639dc8a774f15b1ca07ab1605b994fd3523), enabling renaming an entry in the TuC and re-adding the original entry from the interpreted MRG.
